// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAun319tQDjk-lbOJ3dNm_-EwPU38YIWJY',
    appId: '1:759653016474:web:b1662ab46eb01ae49b9023',
    messagingSenderId: '759653016474',
    projectId: 'fruit-salad-17ba5',
    authDomain: 'fruit-salad-17ba5.firebaseapp.com',
    storageBucket: 'fruit-salad-17ba5.appspot.com',
    measurementId: 'G-0EWKD4KKVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF8AxJQLqri2bY-NKKaTldVJ9Ec6Gsqow',
    appId: '1:759653016474:android:6edd82c16969efb59b9023',
    messagingSenderId: '759653016474',
    projectId: 'fruit-salad-17ba5',
    storageBucket: 'fruit-salad-17ba5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNoJGZgiRA-ig0igy4I3WmM6jshAPoRBM',
    appId: '1:759653016474:ios:8a4087325a9552509b9023',
    messagingSenderId: '759653016474',
    projectId: 'fruit-salad-17ba5',
    storageBucket: 'fruit-salad-17ba5.appspot.com',
    iosBundleId: 'com.example.saladApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNoJGZgiRA-ig0igy4I3WmM6jshAPoRBM',
    appId: '1:759653016474:ios:6bdacc54050236cd9b9023',
    messagingSenderId: '759653016474',
    projectId: 'fruit-salad-17ba5',
    storageBucket: 'fruit-salad-17ba5.appspot.com',
    iosBundleId: 'com.example.saladApplication.RunnerTests',
  );
}
